import asyncio
import logging
from openai import AsyncOpenAI

# from config import OPENAI_API_KEY, OPENAI_IMAGE_MODEL, OPENAI_MODEL
import os
client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY", "empty"))
logger = logging.getLogger(__name__)


async def generate_image(
        prompt: str,
        style_prompt: str,
        reference_image_url: str,
        is_reference_image_human_face: bool = False) -> bytes:
    """
    Use the Response API with OPENAI_IMAGE_MODEL (default: gpt-image-1),
    Args:
        Prompt
        Style Prompt:
        reference_image_url: the reference Image URL directly as an input_image
    Returns the raw image bytes
    """

    logger.info(
        f"Generating image with prompt: {prompt}, style_prompt: {style_prompt}, reference_image_url: {reference_image_url}, is_reference_image_human_face: {is_reference_image_human_face}")
    full_prompt = (
        f"{style_prompt}\n\n"
        f"User request: {prompt}\n\n"
    )

    if is_reference_image_human_face:
        full_prompt += "IMPORTANT: The generated thumbnail MUST prominently feature the person shown in the provided reference headshot photo. Keep their likeness accurate."

    logger.info(f"{full_prompt=}")

    try:
        response = await client.responses.create(
            model="gpt-5.5",
            input=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_image",
                            "image_url": reference_image_url  # Nested dictionary is required
                        },
                        {
                            "type": "input_text",
                            "text": full_prompt
                        },
                    ]
                }
            ],
            tools=[
                {
                    "type": "image_generation",
                    "model": "gpt-image-2",
                    "quality": "medium",
                    "output_format": "png",

                }
            ]
        )
    except Exception as e:
        logger.error(f"Error during image generation: {str(e)}")
        raise RuntimeError(f"Image generation failed: {str(e)}")

    for item in response.output:
        # Check if the output item contains the generated image result
        if item.type == "image":
            # If the API returns raw bytes, return them;
            # if it returns base64 string, decode it.
            return item.image

        # Some versions return via tool_call_result
        if item.type == "image_generation_call":
            return item.result  # Assuming the SDK handles the byte conversion

    raise RuntimeError("No image generated by the LLM model")


if __name__ == "__main__":

    prompt = "Soft diffused natural lighting, monochromatic palette with subtle accents, plenty of negative space, sleek lines, studio photography, airy and uncluttered aesthetic, high-end product design feel."
    style_prompt = "Generate a thumbnail for showing my first trip to the mumbai streets."
    asyncio.run(generate_image(
        prompt=prompt,
        style_prompt=style_prompt,
        reference_image_url=""))

    # asyncio.run(function())