import base64
import logging
from openai import AsyncOpenAI

from config import OPENAI_API_KEY, OPENAI_IMAGE_MODEL, OPENAI_MODEL

client = AsyncOpenAI(api_key=OPENAI_API_KEY)
logger = logging.getLogger(__name__)

async def generate_image(
        prompt: str, 
        style_prompt: str, 
        reference_image_url: str, 
        is_reference_image_human_face: bool = False) -> bytes:
    """
    Use the Response API with OPENAI_IMAGE_MODEL (default: gpt-image-1),
    Args:
        Prompt
        Style Prompt:
        reference_image_url: the reference Image URL directly as an input_image
    Returns the raw image bytes
    """

    logger.info(f"Generating image with prompt: {prompt}, style_prompt: {style_prompt}, reference_image_url: {reference_image_url}, is_reference_image_human_face: {is_reference_image_human_face}")   
    full_prompt = (
        f"{style_prompt}\n\n"
        f"User request: {prompt}\n\n"
    )

    if is_reference_image_human_face:
        full_prompt += "IMPORTANT: The generated thumbnail MUST prominently feature the person shown in the provided reference headshot photo. Keep their likeness accurate."

    logger.info(f"{full_prompt = }")   
    
    response = await client.responses.create(
        model=OPENAI_MODEL,
        input=[
            {
                "role": "user",
                "content": [
                    {"type": "input_image", "url": reference_image_url},
                    {"type": "text", "text": full_prompt},
                ]
            }
        ],
        tools=[
            {
                "type": "image_generation",
                "model": OPENAI_IMAGE_MODEL,
                "quality": "standard",
                "output_format": "png"
            }
        ]
    )


    for item in response.output:
        if item.type == "image_generation_call":
            return base64.b64encode(item.result)
        
    raise RuntimeError("No image generated by the LLM model")
